import React from 'react';
import { LegalDocument } from './LegalDocument';

interface TermsOfServiceProps {
  onBack: () => void;
}

const termsOfServiceContent = `TERMS OF SERVICE FOR SLATEONE STUDIO  
Last Updated: 26/01/2026

1. INTRODUCTION AND ACCEPTANCE 1.1. These Terms of Service ("Terms") govern your use of the SlateOne Studio website and script breakdown services ("Service"). 1.2. By creating an account or uploading a script, you agree to be bound by these Terms. 1.3. These Terms form a binding contract between you ("User") and Celebration House Entertainment cc ("we", "us", or "SlateOne"), a private company registered in South Africa.

2. THE SERVICES 2.1. SlateOne provides automated and semi-automated script breakdown, scheduling, and budgeting tools for the film production industry. 2.2. We grant you a limited, non-exclusive, non-transferable license to access and use the Service for your internal business or personal production needs.

3. USER CONTENT AND INTELLECTUAL PROPERTY 3.1. Your Ownership: You retain full ownership, copyright, and all intellectual property rights to any scripts, treatments, documents, or data you upload to the Service ("User Content"). 3.2. License to SlateOne: You grant SlateOne a worldwide, royalty-free license to host, copy, process, and display your User Content solely as necessary to provide the Service to you. 3.3. No Public Performance: SlateOne shall not publish, sell, distribute, or publicly perform your User Content without your explicit written consent. 3.4. Output Data: You own all reports, schedules, budgets, and breakdown data generated by the Service from your User Content.

4. CONFIDENTIALITY 4.1. Definition: "Confidential Information" includes your scripts, story details, character arcs, casting wish-lists, and production budgets. 4.2. Our Obligation: SlateOne agrees to treat all User Content as strictly confidential. We will not disclose User Content to any third party except: a) To our authorized service providers (e.g., cloud hosting) who are bound by confidentiality obligations; b) As required by law or a valid court order. 4.3. Security: We employ industry-standard encryption (SSL/TLS) and access controls to protect your Confidential Information. However, you acknowledge that no digital transmission is 100% secure.

5. ACCEPTABLE USE 5.1. You agree not to: a) Upload content that you do not have the rights to use; b) Reverse engineer or attempt to extract the source code of the SlateOne platform; c) Share your account credentials with multiple users (unless on the Team License, where each additional team member requires a paid seat); d) Use the Service to upload malware or malicious code.

6. PAYMENT AND CANCELLATION 6.1. The Service is offered on two plans, priced in South African Rand (ZAR): a) Pay-Per-Breakdown, charged on a pay-as-you-go basis for each breakdown you run; and b) the Team License, billed monthly or annually in advance (with a two-month discount for annual billing) plus a per-seat fee for each team member you add. 6.2. The Team License renews automatically each billing period; you may cancel at any time and access will continue until the end of the current billing period. Pay-Per-Breakdown charges are once-off and non-recurring. 6.3. Payments are processed securely by our third-party payment provider. 6.4. Refunds are handled in accordance with the Consumer Protection Act (CPA) and our Refund Policy.

7. LIMITATION OF LIABILITY 7.1. Service "As Is": The Service is provided "as is" without warranties of accuracy. You are responsible for verifying the accuracy of any script breakdown data before making financial production decisions. 7.2. Liability Cap: To the maximum extent permitted by the CPA: a) SlateOne shall not be liable for any indirect, consequential, or special damages (including loss of data, production delays, or loss of profits); b) Our total liability for any claim shall not exceed the amount you paid to us in the six (6) months preceding the claim.

8. GOVERNING LAW AND DISPUTE RESOLUTION 8.1. These Terms are governed by the laws of the Republic of South Africa. 8.2. Any disputes shall be subject to the exclusive jurisdiction of the courts located in, South Africa.`;

export const TermsOfService: React.FC<TermsOfServiceProps> = ({ onBack }) => {
  return (
    <LegalDocument
      title="Terms of Service"
      content={termsOfServiceContent}
      onBack={onBack}
    />
  );
};
